name: mindease_web
description: "MindEase - AI-Powered Emotional Support & Counsellor Connection"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.0
  font_awesome_flutter: ^10.6.0
  fl_chart: ^0.68.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  animations: ^2.0.11
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.1.0
  
  # Firebase Dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_analytics: ^10.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/